### ISSUE TITLE
Refactor to use gallery view for both tools and workflows 

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/ofo-website-3#1]
As discussed internally, we'd like to supersede most of the content in [ofo-docs](https://github.com/open-forest-observatory/ofo-docs) with this website. One part of this would be adding a gallery view for each of the OFO tools (e.g. automate-metashape, geograypher, OFO-R, etc.) and also another one for projects/workflows that use these tools. The later may only consist of a few items for the time being.

**Comment by youngdjn** [comment]
Made some progress on this, using manually created tables of contents (as opposed to auto-generated gallery views) to have a bit more control, but we could later switch to an automated gallery view if desired. I populated the Workflows section with come skeleton content. Do you think this issue can be closed?

**Comment by russelldj** [comment]
Looks good!
